# Generated by Django 4.2.28 on 2026-02-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
