# Generated by Django 5.0.6 on 2026-02-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_customuser_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('Other', 'Other')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, choices=[('Back', 'Backend'), ('Front', 'Frontend'), ('PM', 'PM'), ('Design', 'Design')], default=None, max_length=50, null=True),
        ),
    ]
