# Generated by Django 4.2.28 on 2026-02-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_customuser_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('Other', 'Other')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, choices=[('Back', 'Backend'), ('Front', 'Frontend'), ('PM', 'PM'), ('Design', 'Design')], default=None, max_length=50),
        ),
    ]
