# Generated by Django 4.2.28 on 2026-02-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_customuser_activation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('Other', 'Other')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, choices=[('Back', 'Backend'), ('Front', 'Frontend'), ('PM', 'PM'), ('Design', 'Design')], default=None, max_length=50, null=True),
        ),
    ]
