# Generated by Django 4.2.28 on 2026-02-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_customuser_department_and_more'),
        ('account', '0013_customuser_github_customuser_linkedin_and_more'),
    ]

    operations = [
    ]
