# Generated by Django 5.2.11 on 2026-02-07 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(unique=True, verbose_name='Номер дня')),
                ('title', models.CharField(help_text='Например: День 1. Знакомство с компанией', max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание целей дня')),
                ('instructions', models.TextField(verbose_name='Текстовые инструкции')),
                ('deadline_time', models.TimeField(help_text='Формат ЧЧ:ММ', verbose_name='Дедлайн сдачи отчёта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'День онбординга',
                'verbose_name_plural': 'Дни онбординга',
                'db_table': 'onboarding_days',
                'ordering': ['order', 'day_number'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('link', 'Ссылка'), ('video', 'Видео (YouTube/Vimeo)'), ('image', 'Изображение'), ('file', 'Файл')], max_length=20, verbose_name='Тип материала')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('file', models.FileField(blank=True, null=True, upload_to='onboarding/media/', verbose_name='Файл')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('onboarding_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_materials', to='onboarding_app.onboardingday', verbose_name='День онбординга')),
            ],
            options={
                'verbose_name': 'Медиа-материал',
                'verbose_name_plural': 'Медиа-материалы',
                'db_table': 'onboarding_media',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_done', models.TextField(blank=True, verbose_name='Что сделал')),
                ('what_will_do', models.TextField(blank=True, verbose_name='Что буду делать')),
                ('problems', models.TextField(blank=True, verbose_name='Какие проблемы возникли')),
                ('attachment_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на результат')),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to='onboarding/reports/', verbose_name='Файл с результатом')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлен'), ('accepted', 'Принят'), ('revision', 'На доработку'), ('rejected', 'Отклонён')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('reviewer_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий проверяющего')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL, verbose_name='Стажёр')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='Проверяющий')),
                ('onboarding_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='onboarding_app.onboardingday', verbose_name='День онбординга')),
            ],
            options={
                'verbose_name': 'Ежедневный отчёт',
                'verbose_name_plural': 'Ежедневные отчёты',
                'db_table': 'daily_reports',
                'ordering': ['-created_at'],
                'unique_together': {('intern', 'onboarding_day')},
            },
        ),
    ]
