# Generated by Django 5.2.11 on 2026-02-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('complaint', 'Жалоба'), ('suggestion', 'Предложение'), ('review', 'Отзыв')], max_length=20, verbose_name='Тип обращения')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Анонимное')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('contact_type', models.CharField(blank=True, choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], max_length=20, null=True, verbose_name='Тип контакта')),
                ('contact_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакт')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В обработке'), ('resolved', 'Решено')], default='new', max_length=20, verbose_name='Статус')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий администратора')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'db_table': 'feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
