# Generated by Django 5.2.11 on 2026-02-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('content_type', models.CharField(choices=[('link', 'Ссылка'), ('file', 'Файл')], max_length=10, verbose_name='Тип контента')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('file', models.FileField(blank=True, null=True, upload_to='regulations/', verbose_name='Файл')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Регламент',
                'verbose_name_plural': 'Регламенты',
                'db_table': 'regulations',
                'ordering': ['order', 'title'],
            },
        ),
    ]
