# Generated by Django 5.2.11 on 2026-02-07 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_working_day', models.BooleanField(default=False, help_text='Галочка если это перенесенный рабочий день', verbose_name='Рабочий день')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Праздник/Выходной',
                'verbose_name_plural': 'Праздники и выходные',
                'db_table': 'holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WorkScheduleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: График 5/2', max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('work_days', models.JSONField(default=list, help_text='Список номеров рабочих дней недели: [1,2,3,4,5] для Пн-Пт', verbose_name='Рабочие дни')),
                ('start_time', models.TimeField(verbose_name='Начало рабочего дня')),
                ('end_time', models.TimeField(verbose_name='Окончание рабочего дня')),
                ('lunch_start', models.TimeField(blank=True, null=True, verbose_name='Начало обеда')),
                ('lunch_end', models.TimeField(blank=True, null=True, verbose_name='Окончание обеда')),
                ('breaks', models.JSONField(blank=True, help_text='JSON: [{"start": "10:00", "end": "10:15", "name": "Кофе-брейк"}]', null=True, verbose_name='Дополнительные перерывы')),
                ('is_default', models.BooleanField(default=False, verbose_name='График по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Тип графика работы',
                'verbose_name_plural': 'Типы графиков работы',
                'db_table': 'work_schedule_types',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedule', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('schedule_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.workscheduletype', verbose_name='Тип графика')),
            ],
            options={
                'verbose_name': 'График пользователя',
                'verbose_name_plural': 'Графики пользователей',
                'db_table': 'user_schedules',
            },
        ),
    ]
