# Generated by Django 5.2.11 on 2026-02-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content_type', models.CharField(choices=[('text', 'Текст'), ('link', 'Ссылка'), ('file', 'Файл')], max_length=10, verbose_name='Тип контента')),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='Текстовое содержимое')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('file', models.FileField(blank=True, null=True, upload_to='instructions/', verbose_name='Файл')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Инструкция',
                'verbose_name_plural': 'Инструкции',
                'db_table': 'instructions',
            },
        ),
    ]
